### ISSUE TITLE
Dataset provision

### ISSUE THREAD

**Issue by amblee0306** [didi/hetsann#2] opened 2020-01-10 07:21 UTC
Hi there, 

Just came across your paper and would be great if we can get the dataset utilised and also the way to preprocess the dataset.

Thanks
Regards

**Comment by xhhszc** [comment] 2021-02-20 02:39
Duplicate of # 1

**Closed** 2021-02-20 02:39 UTC

**Comment by xhhszc** [comment] 2021-02-20 02:41
Duplicate of #1
